---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - volumegroup.storage.dell.com
    resources:
      - dellcsivolumegroupsnapshots
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - volumegroup.storage.dell.com
    resources:
      - dellcsivolumegroupsnapshots/finalizers
    verbs:
      - update
  - apiGroups:
      - volumegroup.storage.dell.com
    resources:
      - dellcsivolumegroupsnapshots/status
    verbs:
      - get
      - patch
      - update
