name: Workflow
on:
  push:
jobs:
  test:
    name: Run Go unit tests and check package coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          repository: 'dell/csi-volumegroup-snapshotter'
          path: 'csi-volumegroup-snapshotter'
      - name: Run unit tests and check package coverage
        uses: dell/common-github-actions/go-code-tester@try-test-fix
        with:
          threshold: 80
          # test-folder should be accurate for all csi-drivers
          skip-list: "podmon/test/ssh"
