name: Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  code-check:
    name: Check Go formatting, linting, vetting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          repository: 'dell/csi-volumegroup-snapshotter'
          path: 'csi-volumegroup-snapshotter'
          # change these to your driver name
      - name: Run unit tests and check package coverage
        uses: dell/common-github-actions/go-code-tester@try-test-fix
        # set these three to appropriate values
        with:
          threshold: 90
          # test-folder should be accurate for all csi-drivers
          skip-list: "podmon/test/ssh"
